spring:
  application:
    name: itoken-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.191.134:8761/eureka/,http://192.168.191.134:8861/eureka/,http://192.168.191.134:8961/eureka/
